version: "3"
services:
  app:
    image: dogutechio/test-ffmpeg:latest
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - 3000:3000
